config/routes.rb
Rails.application.routes.draw do
  root to: 'groups#index'
  resources :groups
  resources :users, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  before_validation :strip_text_fields

  def strip_text_fields
    self.attributes.each do |field, val|
      self.send(field).strip! if val.respond_to?(:strip)
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :members, class_name: "User", through: :memberships
  has_many :roles, through: :memberships

  # filter on the has_many to get the :through result we want (i.e. organizers)
  has_many :organizer_memberships, -> { joins(:role).where("roles.name = ?", 'Organizer') },
    class_name: "Membership"
  has_many :organizers, through: :organizer_memberships, source: :member do
    def names
      self.map(&:name)
    end
  end

  validates :name, presence: true, uniqueness: true

  def organizer_names
    memberships.organizers.map { |org| org.member.name }
  end

end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :member, class_name: "User", foreign_key: :user_id
  belongs_to :group
  belongs_to :role

  validates :user_id, presence: true, uniqueness: { scope: :group_id }
  validates :group_id, presence: true, uniqueness: { scope: :user_id }
  validates :role_id, presence: true
  before_save :enforce_latest_president

  # add scope :organizers, :presenters, :participants
  %w(Organizer Presenter Participant).each do |role|
    scope "#{role.downcase}s".to_sym, -> {
      joins(:role).where(roles: { name: role }).references(:roles)
    }
  end

  def self.reassign_other_presidents(group_id, except=nil)
    president = Role.find_by_name("President")
    organizer = Role.find_by_name("Organizer")
    records = Membership.where(group_id: group_id, role_id: president)
    if except.present?
      records.where.not(id: except).update_all(role_id: organizer)
    else
      records.update_all(role_id: organizer)
    end
  end

  def enforce_latest_president
    return unless role.name.eql?("President")
    presidents = Membership.where(group_id: group_id, role_id: role_id)
    if new_record?
      self.class.reassign_other_presidents(group_id) if presidents.size > 0
    else
      self.class.reassign_other_presidents(group_id, id) if presidents.size > 0 && !presidents.pluck(:id).include?(id)
    end
  end

end

app/models/role.rb
class Role < ApplicationRecord
  has_many :memberships
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :groups, through: :memberships, as: :member
  has_many :roles, through: :memberships

  validates :first_name, presence: true, uniqueness: { scope: :last_name }
  validates :last_name, presence: true, uniqueness: { scope: :first_name }

  def name
    "#{last_name}, #{first_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :fetch_group, only: [:show, :edit, :update, :destroy]

  def index
    @groups = Group.all.includes(:organizers).order(name: :asc)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      flash[:notice] = "#{@group.name} saved."
      redirect_to action: :index
    else
      process_error_message
      render action: :new
    end
  end

  def show
    @memberships = @group.memberships.includes(:member, :role).
      order("users.last_name ASC, users.first_name ASC")
  end

  def edit
  end

  def update
    if @group.update_attributes(group_params)
      flash[:notice] = "#{@group.name} updated."
      redirect_to action: :index
    else
      process_error_message
      render action: :edit
    end
  end

  def destroy
    if @group.destroy
      flash[:notice] = "Group '#{@group.name}' has been deleted."
    else
      flash[:error] = "Unable to delete group '#{@group.name}'."
    end
    redirect_to action: :index
  end

  private
  def group_params
    params.require(:group).permit(:name)
  end

  def fetch_group
    @group = Group.find_by_id(params[:id])
    if @group.blank?
      flash[:error] = "Can't find group with that ID"
      return redirect_to action: :index
    end
  end

  def process_error_message
    return unless @group.present?
    message = group_params.keys.map {
      |field| "#{field} (#{@group.send(field)}) " + @group.errors.messages[field.to_sym].join(", ")
    }.join("<br/>")
    flash[:error] = message.html_safe
  end

end

app/controllers/users_controller.rb
require 'csv'
class UsersController < ApplicationController

  def create
    counter = 0
    starting_users = User.count
    starting_groups = Group.count
    failures = []
    csv_rows.each do |row|
      # allow row with or without headers
      next if row.first.downcase.strip.scan(/first|name/).present?

      first_name, last_name, group_name, role = row.map(&:strip)

      user = User.where(last_name: last_name).find_by_first_name(first_name)
      # add user if they don't already exist
      user ||= User.create!(first_name: first_name, last_name: last_name)

      group = Group.find_by_name(group_name)
      group ||= Group.create(name: group_name)

      membership = Membership.where(group_id: group.id).find_by_user_id(user.id)
      membership ||= Membership.new(group_id: group.id, user_id: user.id)
      membership.role_id = role_ids[role.downcase]
      if membership.save
        counter += 1
      else
        failures.push("#{last_name}, #{first_name} could not process")
      end
    end
    users_added = User.count - starting_users
    groups_added = Group.count - starting_groups
    flash[:notice] = "Processed #{counter} records. Added #{users_added} users and #{groups_added} groups."
    flash[:error] = failures.join(",") + " could not be processed"
    redirect_to groups_path
  end

  def csv_rows
    csv = params[:csv].read
    if csv.blank?
      flash[:error] = "Missing CSV file"
      return redirect_to groups_path
    end
    CSV.parse(csv, headers: false)
  end

  def role_ids
    @role_ids ||= Role.all.inject({}) { |h, r| h[r.name.downcase] = r.id; h }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.haml
%table
  %tr
    %td= form.label :name
    %td= form.text_field :name
  %tr
    %td
    %td
      = form.submit "Save Group"
      or
      = link_to "Cancel", groups_path

app/views/groups/edit.haml
- content_for :title do
  Edit #{@group.name}

%h1 Edit Group '#{@group.name}'

= form_for @group do |form|
  = render partial: "form", locals: { form: form }

app/views/groups/index.haml
- content_for :title do
  Groups

- if @groups.present?
  %h1 Active Groups
  %table
    %tr
      %th Name
      %th Organizer(s)
      %th
      %th
    - @groups.each do |group|
      %tr
        %td= link_to group.name, group_path(group)
        %td= group.organizers.names.join("<br/>").html_safe
        %td= link_to "Edit", edit_group_path(group)
        %td= link_to "Delete", group_path(group), method: :delete, data: { confirm: "Are you sure?" }

- else
  %h1 No Groups Yet

%hr/
%h3 Actions
%ul
  %li= link_to "Add Group", new_group_path
  %li= link_to "Upload User Data", new_user_path

app/views/groups/new.haml
- content_for :title do
  Add Group

%h1 Add Group

= form_for @group do |form|
  = render partial: "form", locals: { form: form }

app/views/groups/show.haml
%h1
  = @group.name
  Members

%table
  %tr
    %td Name
    %td Role
  - @memberships.each do |membership|
    %tr
      %td= membership.member.name
      %td= membership.role.name

%hr/
%h3 Actions
%ul
  %li= link_to "List Groups", groups_path
  %li= link_to "Add Group", new_group_path
  %li= link_to "Upload User Data", new_user_path

app/views/layouts/application.haml
!!!
%html{ lang: "en" }
  %head
    %title
      = yield :title

    = javascript_include_tag :application
    = stylesheet_link_tag :application
    = csrf_meta_tag

  %body
    .container
      - flash.each do |flash_type, message|
        %div{ class: "flash #{flash_type}" }= message

      = yield

app/views/users/new.haml
%h1 Upload User CSV

%p
  For Users the app should take a CSV file of the following format:
  %br/
  First Name, Last Name, Group Name, Role in Group

= form_with url: users_path, local: true do |form|
  %table
    %tr
      %td= form.label :select_csv_file
      %td= form.file_field :csv
    %tr
      %td
      %td
        = form.submit "Upload Users"
        or
        = link_to "Cancel", groups_path